<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>input mapping</name>
  <uuid>92a08762-e4b9-4efa-847d-8cbd8a77e87f</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new ML model input where
        the age is age, 
        the bmi is bmi, 
        the bp is bp, 
        the gender is gender ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
