<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output</name>
  <uuid>b617fb37-3c4a-4fb4-95ed-196eb22a5f8e</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to the prediction of 'ML model invocation'  ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
